Feature/is equal
bitfinexcom/lib-js-util-base pull request #16
Opened 2023-11-20 19:03 UTC by dictor93

### Description:
Created isEqual function which deeply compares two items

### New features:
- [x] isEqual

### PR status:
- [x] Version bumped
- [x] Change-log updated
- [x] Tests added or updated
- [x] PR keeps 100% test coverage
- [x] Type definition updated
- [x] Readme updated
- [x] Linter is applied
- [x] Const arrow functions are used instead of pure function definitions where applicable
- [x] Functions are listed in alphabetic order in index.js, index.d.ts and readme

2023-11-20 19:18 UTC, oliverbitfinex approved these changes

2023-11-24 09:24 UTC, ezewer approved these changes
looks good to me!

2023-11-24 09:36 UTC, ezewer requested changes
Required changes

2023-11-24 09:36 UTC, ezewer commented on src/isEqual.js
> +const { objectsDeepEqual, strictEqual } = require('./util')
Add directly using: 
const objectsDeepEqual = require('./objectsDeepEqual')
const strictEqual = require('./strictEqual')

2023-11-24 09:36 UTC, ezewer commented on src/util/index.js
> +'use strict'
Delete this file!

2023-11-26 23:57 UTC, ezewer approved these changes
looks good to me!

2023-11-28 23:13 UTC, ezewer approved these changes
looks good to me!

2023-11-29 00:03 UTC, merged

2023-11-29 12:42 UTC, vigan-abd commented on src/util/objectsDeepEqual.js
> +'use-strict'
this file doesn't respect rule ` PR keeps 100% test coverage`, @dictor93 please open a PR with remaining cases

2023-11-29 12:43 UTC, vigan-abd commented on src/util/objectsDeepEqual.js
> +'use-strict'
same goes for isEqual file