feat: object freeze deep
bitfinexcom/lib-js-util-base pull request #17
Opened 2023-11-29 12:47 UTC by vigan-abd

### Description:
This PR adds utility for deep freezing objects

### Breaking changes:
- [ ]

### New features:
- deep freeze object

### Fixes:
- [ ]

### PR status:
- [x] Version bumped
- [x] Change-log updated
- [x] Tests added or updated
- [ ] PR keeps 100% test coverage -> new feature has 100% coverage but some existing ones not
- [x] Type definition updated
- [x] Readme updated
- [x] Linter is applied
- [x] Const arrow functions are used instead of pure function definitions where applicable
- [x] Functions are listed in alphabetic order in index.js, index.d.ts and readme

2023-11-29 13:07 UTC, yaaminu requested changes

2023-11-29 13:07 UTC, yaaminu commented on test/freezeDeep.js
> +describe('freezeDeep', () => {
The feezeDeep utility method would work for arrays and deeply nested arrays too but It'd be better if you could also test to validate that too.

`{foo:'bar', baz:[3, 34, {foo:'bar'}], [3, ['a', 'b','d']]}` and `['bar', 'baz', 'foo', {foo:'bar'}, 3]`

2023-11-30 02:00 UTC, ezewer approved these changes
looks good to me!

2023-11-30 09:00 UTC, yaaminu approved these changes

2023-12-01 13:30 UTC, merged