Add max and min utils
bitfinexcom/lib-js-util-base pull request #19
Opened 2023-12-06 08:27 UTC by ZIMkaRU

### Description:

This PR adds `max` and `min` utils

### New features:
- [x] adds `max` util
- [x] adds `min` util

### PR status:
- [x] Version bumped
- [x] Change-log updated
- [x] Tests added or updated
- [x] PR keeps 100% test coverage
- [x] Type definition updated
- [x] Readme updated
- [x] Linter is applied
- [x] Const arrow functions are used instead of pure function definitions where applicable
- [x] Functions are listed in alphabetic order in index.js, index.d.ts and readme

2023-12-08 00:06 UTC, dictor93 requested changes
Small comments. The rest LGTM!

2023-12-08 00:06 UTC, dictor93 commented on src/max.js
> +const min = (array) => {
```suggestion
const max = (array) => {
```

2023-12-08 00:06 UTC, dictor93 commented on src/max.js
> +module.exports = min
```suggestion
module.exports = max
```

2023-12-08 00:06 UTC, dictor93 commented on src/util/determineExtremumValue.js
> +      return prev
Seems, this condition is not covered by tests

2023-12-08 11:01 UTC, ZIMkaRU commented on src/max.js
> +const min = (array) => {
indeed, thanks for typo detection

2023-12-08 17:01 UTC, dictor93 commented
lgtm

2023-12-08 17:02 UTC, dictor93 approved these changes
LGTM!

2023-12-11 00:05 UTC, ezewer approved these changes
Code looks good to me, please add a test for letters as to prove this also works for text

2023-12-11 15:55 UTC, merged