Feature/extend pick functionality
bitfinexcom/lib-js-util-base pull request #20
Opened 2023-12-07 02:56 UTC by dictor93

### Description:
Extended pick feature functionality by adding multiple path arguments and allowing nested pick using string dot path notation or array path variant

### PR status:
- [x] Version bumped
- [x] Change-log updated
- [x] Tests added or updated
- [x] PR keeps 100% test coverage
- [x] Linter is applied
- [x] Const arrow functions are used instead of pure function definitions where applicable
- [x] Functions are listed in alphabetic order in index.js, index.d.ts and readme

2023-12-07 05:52 UTC, dictor93 commented
[Related PR](https://github.com/bitfinexcom/bfx-core-kyc-js/pull/1026)

2023-12-08 20:31 UTC, jarco-develop approved these changes
LGTM

2023-12-11 00:18 UTC, ezewer reviewed
Code looks good, split in lines for better reading.

2023-12-11 00:18 UTC, ezewer commented on test/pick.js
> +    assert.deepStrictEqual(pick({ a: 1, b: 2, c: 3, d: 4 }, ['a', 'b'], 'd'), { a: 1, b: 2, d: 4 })
Can we split in shorter lines please?

2023-12-11 11:02 UTC, ezewer approved these changes
looks good to me!

2023-12-11 17:29 UTC, grantfayvor approved these changes
lgtm!

2023-12-11 17:38 UTC, vigan-abd requested changes

2023-12-11 17:38 UTC, vigan-abd commented on CHANGELOG
> +- feat: exrtended pick functionality by using multiple path parameters and nested pick
typo

2023-12-11 17:38 UTC, vigan-abd commented
also branch has conflicts

2023-12-11 17:46 UTC, vigan-abd requested changes

2023-12-11 17:46 UTC, vigan-abd commented on CHANGELOG
> +- feat: extended pick functionality by using multiple path parameters and nested pick
newline missing

2023-12-11 17:47 UTC, vigan-abd approved these changes

2023-12-11 17:59 UTC, merged