Feature/flow
bitfinexcom/lib-js-util-base pull request #28
Opened 2024-05-03 18:46 UTC by dictor93

### Description:
Added feature `flow` which generate a composite function that returns the result of provided functions called by the chain; each previous function result passes as the argument of the next function in the chain

### New features:
- [ ]flow

### PR status:
- [ ] Version bumped
- [ ] Change-log updated
- [ ] Tests added or updated
- [ ] PR keeps 100% test coverage
- [ ] Type definition updated
- [ ] Readme updated
- [ ] Linter is applied
- [ ] Const arrow functions are used instead of pure function definitions where applicable
- [ ] Functions are listed in alphabetic order in index.js, index.d.ts and readme

2024-05-30 10:48 UTC, grantfayvor reviewed
small comment

2024-05-30 10:48 UTC, grantfayvor commented on src/flow.js
> +  return (arg) => fns.reduce((acc, fn) => fn(acc), arg)
lodash version of this function accepts an arbitrary number of arguments. so maybe something like
```suggestion
  return (...args) => fns.reduce((acc, fn) => [fn(...acc)], args)
```

2024-05-31 09:23 UTC, grantfayvor approved these changes
lgtm!

2024-05-31 11:22 UTC, vigan-abd requested changes

2024-05-31 11:22 UTC, vigan-abd commented on src/invert.js
> +  Object.fromEntries(Object.entries(object).map(([key, value]) => [value, key]))
This approach has more lines of code but is more efficient as it has just a single loop
```suggestion
const invert = (object) => {
  const newObject = {}
  for (const key in object) {
    newObject[object[key]] = key
  }
  return newObject
}
```

2024-06-06 20:17 UTC, vigan-abd approved these changes

2024-06-11 08:42 UTC, vigan-abd approved these changes

2024-06-11 08:46 UTC, rjmacarthy approved these changes

2024-06-12 00:01 UTC, ezewer approved these changes
looks good to me!

2024-06-12 15:45 UTC, merged