feat: add resolvePromiseCb and snakeCase
bitfinexcom/lib-js-util-base pull request #32
Opened 2024-08-28 11:11 UTC by jsertx

### Description:
Add `resolvePromiseCb` and `snakeCase` helper 

### Breaking changes:
None

### New features:
- [ ] Add `resolvePromiseCb` helper
- [ ] Add `snakeCase` helper

### Fixes:
- [ ]

### PR status:
- [ ] Version bumped
- [ ] Change-log updated
- [x] Tests added or updated
- [x] PR keeps 100% test coverage
- [x] Type definition updated
- [x] Readme updated
- [x] Linter is applied
- [x] Const arrow functions are used instead of pure function definitions where applicable
- [x] Functions are listed in alphabetic order in index.js, index.d.ts and readme

2024-08-28 14:46 UTC, acamaragl approved these changes

2024-08-28 14:57 UTC, avsek477 approved these changes

2024-08-29 08:52 UTC, vigan-abd requested changes
can you update changelog and package version as well please?

2024-08-29 09:46 UTC, vigan-abd approved these changes

2024-08-29 09:46 UTC, merged